# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'cswat'

Gem::Specification.new do |spec|
  spec.name          = "cswat"
  spec.version       = CSWat::VERSION
  spec.authors       = ["Arash Badie Modiri"]
  spec.email         = ["arashbm@gmail.com"]

  spec.summary       = %q{Fork-ish of Standard Library CSV that handle weired cases}
  spec.description   = %q{CSWat makes dealing with CSV generated by not-so-bright writers easier}
  spec.homepage      = "https://github.com/smartlyio/cswat"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.12"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "minitest", "~> 5.0"
  spec.add_development_dependency "minitest-reporters", "~> 1.1"
  spec.add_development_dependency "test-unit", "~> 3.2.1"
end
